DELETE FROM BOOKS;
INSERT INTO BOOKS (BOOK_ISBN,BOOK_NAME ,BOOK_DESCRIPTION ,BOOK_GENRE ,BOOK_AUTHOR ,  BOOK_PUBLISHER , BOOK_AVAILABLE, BOOK_PUBLISHED_DATE ,  BOOK_LANGUAGE)
VALUES ('A12333','Data Smart','Data engineering','Science','Paelo Carlo','Wiley','Yes','02-02-2005','English');
INSERT INTO BOOKS (BOOK_ISBN,BOOK_NAME ,BOOK_DESCRIPTION ,BOOK_GENRE ,BOOK_AUTHOR ,  BOOK_PUBLISHER , BOOK_AVAILABLE, BOOK_PUBLISHED_DATE ,  BOOK_LANGUAGE)
VALUES ('A12334','History of India','Historial exploration of ancient India','History','Dr Rk Dixit','BR publisher','Yes','02-02-2005','English');
INSERT INTO BOOKS (BOOK_ISBN,BOOK_NAME ,BOOK_DESCRIPTION ,BOOK_GENRE ,BOOK_AUTHOR ,  BOOK_PUBLISHER , BOOK_AVAILABLE, BOOK_PUBLISHED_DATE ,  BOOK_LANGUAGE)
VALUES ('A12335','Bhagavad Gita','Epic stories of Lord Krishna','Religion','SriPrakash','Arihant publisher ltd','Yes','02-02-1995','Hindi');
INSERT INTO BOOKS (BOOK_ISBN,BOOK_NAME ,BOOK_DESCRIPTION ,BOOK_GENRE ,BOOK_AUTHOR ,  BOOK_PUBLISHER , BOOK_AVAILABLE, BOOK_PUBLISHED_DATE ,  BOOK_LANGUAGE)
VALUES ('A12336','Jai Hanuman','Animation Stories of Hanuman','Religion','SriPrakash','Arihant publisher ltd','Yes','11-02-2015','Hindi');
INSERT INTO BOOKS (BOOK_ISBN,BOOK_NAME ,BOOK_DESCRIPTION ,BOOK_GENRE ,BOOK_AUTHOR ,  BOOK_PUBLISHER , BOOK_AVAILABLE, BOOK_PUBLISHED_DATE ,  BOOK_LANGUAGE)
VALUES ('A12337','Computer microprocesser','Microprocssor engineering','Science','Paelo Carlo','Wiley','Yes','02-02-2001','English');



DELETE FROM AUTHORS;
INSERT INTO AUTHORS(AUTHOR_NAME,AUTHOR_LOCATION )
VALUES ('Paelo Carlo','London');
INSERT INTO AUTHORS(AUTHOR_NAME,AUTHOR_LOCATION )
VALUES ('Dr Rk Dixit','Delhi');
INSERT INTO AUTHORS(AUTHOR_NAME,AUTHOR_LOCATION )
VALUES ('SriPrakash','Chennai');
