CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ISBN VARCHAR(50) UNIQUE ,
    BOOK_NAME VARCHAR(50) NOT NULL,
    BOOK_DESCRIPTION VARCHAR(300),
    BOOK_GENRE VARCHAR(100),
    BOOK_AUTHOR VARCHAR(200) NOT NULL,
    BOOK_PUBLISHER VARCHAR(200),
    BOOK_AVAILABLE CHAR(10),
    BOOK_PUBLISHED_DATE VARCHAR(100),
    BOOK_LANGUAGE VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(200) NOT NULL,
    AUTHOR_LOCATION VARCHAR(100)
 );